import protection from '../img/protection.png';
import implants from '../img/implants.png';
import care from '../img/care.png';
import whitening from '../img/whitening.png';
import calculus from '../img/calculus.png';
import prevention from '../img/prevention.png';

export const services = [
    {
        id: 1,
        name: "Protection",
        title: "There are only 2 dental specialties that only focus on dental esthetics: Prosthodontics and Orthodontics",
        desc: "In order that you may understand whence every born error is the pleasure of accusing and praising the pain, I will open the whole thing, and will explain the very things which were said by that inventor of the truth and as it were the architect of the blessed life. For no one rejects or hates or shuns pleasure, because it is pleasure itself, but because great pains result from those who do not know how to follow pleasure by reason; but times of such a nature do not occur, that he may seek some great pleasure by toil and pain. For, to the slightest degree, who of us undertakes any laborious physical exercise, except to obtain some advantage from it? Who, however, rightfully condemns him, who wishes to be in that pleasure, which no annoyance obtains, or him who shuns that pain, by which no pleasure can be obtained? But we both accuse and deem them most worthy of just hatred, who, soothed by the flattery of the present pleasures, and corrupted, do not foresee what pains and what troubles they will receive, blinded by desire; And the distinction between these things is easy and easy. For in free time, when the choice of choosing is unfettered for us, and when nothing prevents us from being able to do what is most pleasing, every pleasure must be taken up, and every pain must be avoided. But in certain times, and often due to obligations or necessities of life, it will happen that both pleasures must be repudiated and annoyances not accepted. Accordingly, the choice of those things is bound here by the wise man, so that either by rejecting his pleasures, he may obtain at other times greater pleasures, or drive back the more severely endured pains.",
        img: protection,
        route: "protection",
    },
    {
        id: 2,
        name: "Implants",
        title: "The implant fixture is first placed, so that it is likely to osseointegrate, then a dental prosthetic is added",
        desc: "The first step in the dental implant process is the development of an individualized treatment plan. The plan addresses your specific needs and is prepared by a team of professionals who are specially trained and experienced in oral surgery and restorative dentistry. This team approach provides coordinated care based on the implant option that is best for you. Next, the tooth root implant, which is a small post made of titanium, is placed into the bone socket of the missing tooth. As the jawbone heals, it grows around the implanted metal post, anchoring it securely in the jaw. The healing process can take from six to 12 weeks. Once the implant has bonded to the jawbone, a small connector post -- called an abutment -- is attached to the post to securely hold the new tooth. To make the new tooth or teeth, your dentist makes impressions of your teeth, and creates a model of your bite (which captures all of your teeth, their type, and arrangement). The new tooth or teeth is based on this model. A replacement tooth, called a crown, is then attached to the abutment. Instead of one or more individual crowns, some patients may have attachments placed on the implant that retain and support a removable denture. Your dentist also will match the color of the new teeth to your natural teeth. Because the implant is secured within the jawbone, the replacement teeth look, feel, and function just like your own natural teeth. Gum disease begins when plaque builds up along and under your gum line. Plaque causes an infection that hurts the gum and bone that hold your teeth in place. A mild form of gum disease may make your gums red, tender, and more likely to bleed. This problem, called gingivitis, can often be fixed by brushing and flossing every day.",
        img: implants,
        route: "implants",
    },
    {
        id: 3,
        name: "Tooth Care",
        title: "We provide a wide range of oral health care services to patients, from routine checkups to fitting braces",
        desc: "Sometimes, false teeth (dentures) are needed to replace badly damaged teeth or teeth lost because of gum disease. Partial dentures may be used to fill in one or more missing teeth. Dentures may feel strange at first. In the beginning, your dentist may want to see you often to make sure the dentures fit. Over time, your gums will change shape, and your dentures may need to be adjusted or replaced. Be sure to let your dentist handle these adjustments. Be careful when wearing dentures because it may be harder for you to feel hot foods and drinks or notice bones in your food. When learning to eat with dentures, it may be easier if you: Start with soft, non-sticky food. Cut your food into small pieces. Chew slowly using both sides of your mouth. Keep your dentures clean and free from food that can cause stains or bad breath. Avoid small crunchy foods that can get trapped under the dentures and hurt your gums. Brush dentures every day with a denture-care product, and soak them in water or a denture-cleansing liquid at night. Be sure to leave them out of your mouth while you sleep to prevent swollen gums.. See your dentist if brushing or flossing causes your gums to bleed or hurts your mouth. If you have trouble flossing, a floss holder may help. Ask your dentist to show you the right way to floss. A more severe form of gum disease, called periodontitis, must be treated by a dentist. If not treated, this infection can lead to sore, bleeding gums, painful chewing problems, and even tooth loss. Teeth are covered in a hard, outer coating called enamel. Every day, a thin film of bacteria called dental plaque builds up on your teeth. The bacteria in plaque produce acids that can harm enamel and cause cavities. Brushing and flossing your teeth can prevent decay, but once a cavity forms, to avoid further damage, a dentist must fix it with a filling.",
        img: care,
        route: "care",
    },
    {
        id: 4,
        name: "Whitening",
        title: "Bleaching methods use carbamide peroxide which reacts with water to form hydrogen peroxide loremis",
        desc: "Teeth whitening is a form of dentistry and should only be carried out by a dentist or another regulated dental professional, such as a dental hygienist or dental therapist, on the prescription of a dentist. Some beauty salons offer teeth whitening, but this is illegal if there's no dental professional present, and it may put your oral health at risk. You can also buy DIY home teeth whitening kits but these may also carry risks. If you have your teeth whitened you'll need to make several visits to the dental surgery over a couple of months. The dentist will take an impression of your teeth to make a mouthguard and tell you how to use it with a bleaching gel. Then, using your mouthguard at home, you regularly apply the gel for a specified period of time over 2 to 4 weeks. Some whitening gels can be left on for up to 8 hours at a time, which shortens the treatment period to 1 week. Laser whitening, also known as power whitening, is another type of teeth whitening system that a dentist can provide. A bleaching product is painted onto your teeth and then a light or laser is shone on them to activate the whitening. Laser whitening takes about an hour. Some home kits don't contain enough whitening product to be effective. Also, if a dental professional isn't doing the whitening, the mouthguard provided may not fit properly so some of the bleaching gel may leak out onto your gums and into your mouth, causing blistering and sensitivity. Teeth whitening carried out in beauty salons by untrained staff or staff without dental qualifications puts your oral health at risk and is also illegal. Don't be afraid to ask simple questions about the types of whitening treatment available, what results you can expect and whether the work is guaranteed for a certain period of time. You may also want to ask them whether there are any risks involved – for example, increasing the sensitivity of your teeth. Try to talk to other people who've had the same treatment or visit another dentist for a second opinion until you feel confident. Always ask for a written treatment plan and price estimate before going ahead.",
        img: whitening,
        route: "whitening",
    },
    {
        id: 5,
        name: "Calculus",
        title: "Types of bridges may vary, depending upon how they are fabricated and the way they anchor to the adjacent teeth",
        desc: "Teeth tartar, also called dental calculus, is a crusty deposit that can trap stains on the teeth and cause discoloration. It creates a strong bond that can only be removed by a dental professional. Tartar formation may also make it more difficult to remove new plaque and bacteria. Individuals vary greatly in their susceptibility to plaque and tartar on teeth. For many of us, these deposits build up faster as we age. If plaque is not removed regularly, and completely, minerals in your saliva combine with plaque to form crystals that harden into tartar. While plaque can be removed by thorough brushing and flossing at home, dental calculus can only be removed by a professional in the dental office. Your dentist or hygienist will use sharp instruments to scrape (scale) the tartar above and below the gumline and smooth the tooth’s surface which helps prevent plaque from adhering and more tartar from forming. The surface of tartar is rough and makes it difficult to remove plaque with a toothbrush and floss. Tartar is unsightly - it can be yellow or even brown as stains accumulate. In addition, since it attracts plaque and makes cleaning at home difficult, it can contribute to tooth decay, bad breath and serious forms of gum disease. Dental calculus, both supra- and subgingival occurs in the majority of adults worldwide. Dental calculus is calcified dental plaque, composed primarily of calcium phosphate mineral salts deposited between and within remnants of formerly viable microorganisms. A viable dental plaque covers mineralized calculus deposits. Levels of calculus and location of formation are population specific and are affected by oral hygiene habits, access to professional care, diet, age, ethnic origin, time since last dental cleaning, systemic disease and the use of prescription medications. In populations that practice regular oral hygiene and with access to regular professional care, supragingival dental calculus formation is restricted to tooth surfaces adjacent to the salivary ducts. Levels of supragingival calculus in these populations is minor and the calculus has little if any impact on oral-health. Subgingival calculus formation in these populations occurs coincident with periodontal disease (although the calculus itself appears to have little impact on attachment loss), the latter being correlated with dental plaque. In populations that do not practice regular hygiene and that do not have access to professional care, supragingival calculus occurs throughout the dentition and the extent of calculus formation can be extreme. In these populations, supragingival calculus is associated with the promotion of gingival recession.",
        img: calculus,
        route: "calculus",
    },
    {
        id: 6,
        name: "Prevention",
        title: "The most important part of preventive dentistry is to brush teeth with fluoride toothpaste approved by ADA",
        desc: "If you don’t take care of your teeth and properly manage your oral health, you may find yourself forking over thousands of dollars in restorative dental care. Did you know that a full mouth reconstruction can cost between $45,000 and $80,000? By practicing preventive dentistry, you can safeguard yourself from these exorbitant dental costs. Preventive dentistry emphasizes the importance of ongoing hygiene procedures and daily practices to prevent tooth decay and other dental diseases and conditions. Effective preventive dentistry combines at-home oral care by patients with chairside treatments and counseling by dental professionals. For example, the American Dental Association (ADA) recommends a minimum of two dental checkups each year for professional cleaning and management of any developing conditions. Adhering to this recommendation can help your dentist stop dental disease in its earliest stages, protecting your smile and limiting your expense. Topical fluorides strengthen existing teeth, making them more decay-resistant. Topical fluorides include toothpastes, mouth rinses and professionally applied fluoride therapies (gels, foams, rinses or varnishes). Many dentists give topical fluoride treatment to children up to age 18. For people with rampant cavities or predispositions to decay – such as people wearing orthodontic appliances and those with dry mouth – dentists may prescribe a special gel for daily home use. Systemic fluorides are ingested into the body and incorporate into forming tooth structures. Systemic fluorides also can give topical protection because fluoride is present in saliva, which constantly moistens teeth. Systemic fluorides include public water fluoridation or dietary fluoride supplements in the form of tablets, drops or lozenges. However, keep in mind that the type of naturally occurring and added fluoride in the water supply can vary from area to area. Consult with your child’s pedodontist to learn which form will be best for your child based on your area. The ADA recommends that adults and children two years and older use a fluoride toothpaste bearing the ADA Seal of Acceptance. Consult with your child’s dentist if considering the use of toothpaste before age two. The ADA also recommends the use of fluoride mouth rinses, but not for children under six years old, since they may swallow the rinse.",
        img: prevention,
        route: "prevention",
    },
]
